@BaseUrl = https://localhost:7262/api/auth

@GusAccessToken = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjBhMDU3YmE4LWE5YmQtNDFkMy1hNmRmLTllMTM3YWYxNTVjNiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InlvdXNlZmd1czExMUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImV4cCI6MTc2ODYwNTc5MSwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.6KqW-suNFk9f7U2X-5zUP1NSy6xPUFDOB2lv6Ka2L_w
@GusRefreshToken = rpqLauLtjsYsL5dLu/Nu4cKlfdr7YLqI6+BRN2VYofo=

@AwadAccessToken = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFkNDcyMDQ4LWU4MmQtNDdlYS1hMWNlLWU5NWYwMDU2ZDA4MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im1hd2FkQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlZlbmRvciIsImV4cCI6MTc2ODYwNTgyMSwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.DjtKcC2DLUR8v35KoRYBrfrpJoWQXDsuukyMoPsAV9w
@AwadRefreshToken = Z7ggXPsC5cULyzj1mW8yAJUsuSs1jXPyIr7Q3PMhdQ0=

@AdminAccessToken = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjhiYzVlMTQ4LTYxN2EtNDhhYi1hNmVjLTNhOTJmZjU4Yzk0ZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluMUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJWZW5kb3IiLCJleHAiOjE3Njg2NTMyMzcsImlzcyI6ImxvY2FsaG9zdCIsImF1ZCI6ImxvY2FsaG9zdCJ9.Eu94giPEgxTxQ5OJd5n76w2f7AnGaOnZG463qPTkSIA
@AdminRefreshToken = ha0J2AqnP/CJJbm8kOJKe77OJZjCJ96vcRI37Ze8UvA=


###
POST {{BaseUrl}}/login/
Content-Type: application/json

# {
#     "Email": "yousefgus111@gmail.com",
#     "Password": "gus123"
# }
# {
#     "Email": "mawad@gmail.com",
#     "Password": "awad123"
# }
{
    "Email": "admin1@gmail.com",
    "Password": "admin"
}


###
POST {{BaseUrl}}/register/customer
Content-Type: application/json

{
    "FirstName": "Yousef",
    "LastName": "Mohamed",
    "Email": "yousefgus111@gmail.com",
    "Password": "gus123",
    "PhoneNumber": "+2001158689513"
}


###
POST {{BaseUrl}}/register/vendor
Content-Type: application/json

{
    "Email": "mostafagmail.com",
    "PhoneNumber": "+2001095008854",
    "StoreName": "El-Fat7 Store"
}


###
POST {{BaseUrl}}/register/admin
Authorization: Bearer {{AdminAccessToken}}
Content-Type: application/json

{
    "Email": "admin1@gmail.com",
    "Password": "admin",
    "PhoneNumber": "+2001158689555"
}


###
GET  {{BaseUrl}}/private-data
Authorization: Bearer {{AwadAccessToken}}


###
POST {{BaseUrl}}/refresh
Content-Type: application/json

{
    "RefreshToken": "{{GusRefreshToken}}"
}
