@BaseUrl = https://localhost:7262/api

@ProductId = 1155B2C6-CBE9-4E11-A621-97A3295E65FB


###
GET {{BaseUrl}}/products/{{ProductId}}

###


###
GET {{BaseUrl}}/products/Laptop


###
GET {{BaseUrl}}/products?page=1&pageSize=2


###
DELETE {{BaseUrl}}/products/d2eb003f-370f-46cb-9bcc-74a3062e01d0


###
POST {{BaseUrl}}/products
Content-Type: application/json

{
    "Name": "HTML & CSS",
    "Description": "Learning HTML and CSS for beginner",
    "Price": 100,
    "StockQuantity": 40,
    "Category": "Books"
}


###
PUT {{BaseUrl}}/products/{{ProductId}}
Content-Type: application/json

{
    "Category": "Electronics"
}

