@BaseUrl = https://localhost:7262/api/products

@GusAccessToken = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjE2NjJhZDMxLWE5Y2UtNDdlYi1hMzlhLTVlM2Q3Y2UxMDAxMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InlvdXNlZmd1czExMUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImV4cCI6MTc2ODc4NDUwMSwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.dQ1AY6ujm_fhmiKv1myBitw1OAu2kK0s5qix6B-_F2Y
@GusRefreshToken = 4/FU2GGExiHRxbZV0/kDhJ/kwMM04bV59+vi/XJ4hac=

@AwadAccessToken = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFkNDcyMDQ4LWU4MmQtNDdlYS1hMWNlLWU5NWYwMDU2ZDA4MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im1hd2FkQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlZlbmRvciIsImV4cCI6MTc2ODYwNTgyMSwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.DjtKcC2DLUR8v35KoRYBrfrpJoWQXDsuukyMoPsAV9w
@AwadRefreshToken = Z7ggXPsC5cULyzj1mW8yAJUsuSs1jXPyIr7Q3PMhdQ0=

@ProductId = 1bf0735d-1660-441e-b63e-eb08dc1c92b6


###
GET {{BaseUrl}}?page=1&pageSize=5
Authorization: Bearer {{GusAccessToken}}


###
GET {{BaseUrl}}/{{ProductId}}
Authorization: Bearer {{GusAccessToken}}


###
GET {{BaseUrl}}/Skrew
Authorization: Bearer {{GusAccessToken}}


###
DELETE {{BaseUrl}}/d2eb003f-370f-46cb-9bcc-74a3062e01d0
Authorization: Bearer {{AwadAccessToken}}


###
POST {{BaseUrl}}
Authorization: Bearer {{AwadAccessToken}}
Content-Type: application/json

{
    "Name": "Mastering ASP.NET",
    "Description": "Learn and master Asp.Net Core",
    "Price": 100,
    "StockQuantity": 500,
    "Category": "Books"
}


###
PUT {{BaseUrl}}/e813faab-7d96-4e4c-b361-95737ac32eea
Authorization: Bearer {{AwadAccessToken}}
Content-Type: application/json

{
    "Description": "Learn and master Asp.Net Core"
}

